### ISSUE TITLE
ros2 param set string type "Off"

### ISSUE THREAD

**Issue by icolwell-as** [ros2/ros2cli#677]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - Foxy
- DDS implementation:
  - Default
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Declare string parameter from within cpp code.
Attempt to set the parameter from the CLI to the string "Off"
```
ros2 param set /node param_name Off
```

#### Expected behavior

Paremeter is set to the string "Off"

#### Actual behavior

Parameter is changed to boolean type and set to False.

#### Additional information

I tried all the following, none of them allow me to set a string value:
```
ros2 param set /node param_name Off
ros2 param set /node param_name "Off"
ros2 param set /node param_name 'Off'
ros2 param set /node param_name off
```

Is there any way to enforce the type when parsing the passed-in CLI value? or at the very least assume the passed-in value is the same type as the existing parameter type?

Maybe a new `-f`/`--force-type` flag for "force" type?

**Comment by clalancette** [comment]
Thanks for the report.  This is basically unintentional behavior (and hence a bug).

What's happening here is that we are using YAML parsing to parse the value, and it is automatically interpreting certain values (on, off, true, false, etc) as booleans, and then trying to send that to the node.  In Foxy, parameter types are flexible, so it automatically changes the type.  In Rolling, for instance, the `ros2 param set` call fails because there we are enforcing types and this is trying to change the type.

One workaround for all platforms is to do the following:

```
ros2 param set /node param_name "\"off\""
```

Which will make the parameter literally `"off"`.  That's enough to keep it a string, though you'll have to have custom code inside of the node in order to strip the quotes off.  In the meantime, I'll mark this as a bug to look into.

**Comment by clalancette** [comment]
https://github.com/ros2/ros2cli/pull/684 is a potential fix for this, though I don't think we can completely fix it.

With #684 in, running:

```
ros2 param set /node param 'off'
```

will still interpret the argument as a boolean.  But the following would work as an override:

```
ros2 param set /node param '!!str off'
```

**Comment by icolwell-as** [comment]
Thanks for the fix! much appreciated.

**Comment by clalancette** [comment]
You are welcome, happy to help.
