### ISSUE TITLE
ROS 2 daemon process ignores SIGTERM

### ISSUE THREAD

**Issue by cottsay** [ros2/ros2cli#885]
## Bug report

**Required Info:**

- Operating System:
  - Fedora 39
- Installation type:
  -  source
- Version or commit hash:
  - d3cfbd7
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

```
$ ros2 daemon start
$ ps aux | grep ros2
cottsay   736254  0.2  0.4 1859404 78720 pts/26  Sl   13:31   0:00 /usr/bin/python3 -c from ros2cli.daemon.daemonize import main; main() --name ros2-daemon --ros-domain-id 0 --rmw-implementation rmw_fastrtps_cpp
$ kill -TERM 736254
$ ros2 daemon status
The daemon is running
```

#### Expected behavior
Daemon process gracefully stops upon receiving `SIGTERM`.

#### Actual behavior
Daemon process ignores the signal.

**Comment by fujitatomoya** [comment]
i cannot figure out why `SIGINT` and `SIGKILL` just works fine but `SIGTERM`... any thoughts?

```bash
### does not work
kill -TERM 12280
### works
kill -KILL 12280
kill -INT 12280
```

**Comment by clalancette** [comment]
I spent a bit of time digging into this.  I have some idea of what is going on here.

I think we have two bugs.  The first bug is that https://github.com/ros2/ros2cli/blob/d3cfbd7612b5d2707b16da1b900dc772dd88a61c/ros2cli/ros2cli/daemon/__init__.py#L128-L129 needs to also check `rclpy.ok`, since `rclpy` is handling the signals by default.

The second bug is a bit trickier.  It turns out that when we are sitting idle, we will never, ever leave `server.handle_request()` in that loop.  That `handle_request()` uses a `select` statement underneath, but the timeout for that select is set to `2*60*60`, i.e. two hours.  To fix this, I think we need to have two timeouts; one that is the timeout for checking whether we should quit due to a signal (set to 100 milliseconds or something like that), and one which is the overall timeout which defines when the daemon should quit due to inactivity.  I'll give a shot at implementing that.

**Comment by clalancette** [comment]
All right, see #887 for the fixes.
